### ISSUE TITLE
Initialisation d'un compte avec Proxy

### ISSUE THREAD

**Issue by jbpotokar** [nuxeo/nuxeo-drive#41]
Bonjour, 

Lors de la première connexion du drive au serveur, il faut qu'il n'y ait pas de proxy configuré, at qu'on soit en direct avec le serveur. 
Par la suite, lorsque la première connexion a fonctionné, on peut passer en proxy...

JB

**Comment by ataillefer** [comment]
Pourquoi ?

**Comment by jbpotokar** [comment]
Ben je sais pas, mais c'est ce que je constate :-)
J'ai essayé après installation du drive de me connecté, et j'ai eu systématiquement le message me demandant devérifier l'url. 
Puis j'ai changé de réseau, pour en prendre un sans proxy, et ça a fonctionné. 
Y a t-il des logs intéressantes que je doive poster ?

**Comment by ataillefer** [comment]
Si vous êtes derrière un proxy, il faut le considérer lors de la requête de connexion comme pour toutes les autres requêtes, sinon la requête ne passera jamais.
Par défaut le réglage du proxy est à System ce qui permet d'utiliser le proxy configuré au niveau OS (ne marche que sur un proxy non authentifié). Si vous voulez utiliser un autre proxy ou un proxy authentifié, il faut choisir Manual et entrer le proxy sous la forme <host>:<port>

Les logs sont dans ~/.nuxeo-drive/logs/nxdrive.log.

**Comment by jbpotokar** [comment]
Je suis ok la dessus. J'ai bien paramétré le proxy dès la première connexion. Il n'utilise pas d'authentification, et d'ailleurs par la suite il fonctionne correctement. 
Mais cette même config qui fonctionne par la suite ne marche pas pour la requête de connexion, si j'ai bien observé.
Par ailleurs, mais c'est un autre sujet, je n'ai jamais réussi à faire fonctionner le réglage du proxy à System, je dois toujours utiliser manual, mais je soupçonne que c'est parceque c'est un proxy https.

**Comment by ataillefer** [comment]
Pour comprendre il faudrait les logs, si vous pouvez joindre un extrait correspondant au moment où vous tentez de vous connecter avec le proxy configuré.
System + HTTPS doit fonctionner.
Sur quel OS êtes-vous et quelle version de Nuxeo Drive ?

**Comment by jbpotokar** [comment]
Ok. 
OS : windows 7 64b, SP1
Nuxeo Drive : 2.0.0806
logs (j'ai masqué l'url, mais elle est correcte): 
2015-08-06 17:40:52,875 3660 2480 ERROR    nxdrive.wui.settings Error while trying to connect to Nuxeo Drive startup page with URL https://-------------/nuxeo/
Traceback (most recent call last):
  File "nuxeo-drive-client\nxdrive\wui\settings.py", line 200, in _connect_startup_page
  File "C:\Python27\lib\httplib.py", line 973, in request
  File "C:\Python27\lib\httplib.py", line 1007, in _send_request
  File "C:\Python27\lib\httplib.py", line 969, in endheaders
  File "C:\Python27\lib\httplib.py", line 829, in _send_output
  File "C:\Python27\lib\httplib.py", line 791, in send
  File "C:\Python27\lib\httplib.py", line 1172, in connect
  File "C:\Python27\lib\socket.py", line 553, in create_connection
gaierror: [Errno 11004] getaddrinfo failed

**Comment by ataillefer** [comment]
Il est en effet possible que les paramètres de proxy ne soient pas utliisés pour la toute première requête envoyée par Drive.
Je vais regarder.

**Comment by ataillefer** [comment]
Bonjour,
J'ai fait un fix dans le cadre de https://jira.nuxeo.com/browse/NXDRIVE-409
Pouvez-vous SVP tester le dernier build de développement pour Windows :
http://qa.nuxeo.org/jenkins/view/Drive/job/nuxeo-drive-msi/1064/artifact/dist/nuxeo-drive-2.0.807-win32.msi

**Comment by jbpotokar** [comment]
Bonjour,

Ca ne marche pas il semble : 
2015-08-07 15:47:01,790 7020 8476 INFO     nxdrive.manager    Proxy settings successfully updated: ProxySettings<config=Manual, proxy_type=https, server=xxx.xxx.xxx.xxx, port=yyyy, authenticated=False, username=, exceptions=None>
2015-08-07 15:47:36,625 7020 8476 INFO     requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): ----.-------.com
2015-08-07 15:47:49,721 7020 8476 ERROR    nxdrive.wui.settings Error while trying to connect to Nuxeo Drive startup page with URL https://----.-----.com/nuxeo/
Traceback (most recent call last):
  File "nuxeo-drive-client\nxdrive\wui\settings.py", line 195, in _connect_startup_page
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 95, in head
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 50, in request
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 465, in request
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 573, in send
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 431, in send
SSLError: [Errno 2] No such file or directory
2015-08-07 15:48:48,732 7020 8476 INFO     requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): ----.-----.com
2015-08-07 15:48:48,737 7020 8476 ERROR    nxdrive.wui.settings Error while trying to connect to Nuxeo Drive startup page with URL https://----.-----.com/nuxeo/
Traceback (most recent call last):
  File "nuxeo-drive-client\nxdrive\wui\settings.py", line 195, in _connect_startup_page
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 95, in head
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 50, in request
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 465, in request
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 573, in send
  File "C:\Users\jenkins\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 431, in send
SSLError: [Errno 2] No such file or directory

**Comment by ataillefer** [comment]
Se peut-il que votre certificat ne soit pas issu d'une autorité reconnue ?

**Comment by jbpotokar** [comment]
Non, je ne crois pas : il est délivré poa

**Comment by ataillefer** [comment]
Pour le savoir il suffit de taper l'URL HTTPS dans un navigateur qui n'a pas déjà enregistré d'exceptions pour ce certificat et voir s'il y a un avertissement de sécurité.

Dans tous les cas pour l'instant drive ne gère pas bien les histoires de certificats / SSL pour l'authentification. On peut cependant prévoir dans ce cas de se rabattre sur une authentification basique.

**Comment by jbpotokar** [comment]
Bonjour, 

Qu'entendez-vous pas authentificaqtion basique ? Je mets un autre paramétrage ?

**Comment by ataillefer** [comment]
Fixed by https://jira.nuxeo.com/browse/NXDRIVE-409
