### ISSUE TITLE
Nuxeo drive fails to sync documents with facet 'SystemDocument'

### ISSUE THREAD

**Issue by chaselmann** [nuxeo/nuxeo-drive#602]
Documents with the facet 'SystemDocument' can not be synchronized. 

When converting a document to an object of instance 'RemoteFileInfo' the creation and modification date are used to calculate a time stamp. Since these properties are not available for SystemDocuments the synchronization fails

**Comment by chaselmann** [comment]
Exception in thread Thread-13:
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nuxeo-drive\nxdrive\gui\folders_treeview.py", line 279, in load_children_thread
    children = list(self.client.get_children(parent_item))
  File "C:\Users\nuxeo-drive\nxdrive\gui\folders_treeview.py", line 154, in get_children
    RemoteFileInfo.from_dict(root), state=self.get_item_state(root["path"])
  File "C:\Users\nuxeo-drive\nxdrive\objects.py", line 73, in from_dict
    last_update = fs_item["lastModificationDate"] // 1000
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

**Comment by BoboTiG** [comment]
FI we will have a look soon (https://jira.nuxeo.com/browse/NXDRIVE-1417).

**Comment by BoboTiG** [comment]
The code fix has been merged with 448bdc1. I am closing this issue, but keep in mind that such documents are not meant to be synced (https://doc.nuxeo.com/nxdoc/available-facets/#systemdocument).
