### ISSUE TITLE
Installation fails: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-h50k8kag-build/setup.py'

### ISSUE THREAD

**Issue by fbernigaud** [nuxeo/nuxeo-drive#667]
Hello,
I get:
```
> sudo pip3 install --upgrade git+https://github.com/nuxeo/nuxeo-drive.git@release-4.0.0
Collecting git+https://github.com/nuxeo/nuxeo-drive.git@release-4.0.0
  Cloning https://github.com/nuxeo/nuxeo-drive.git (to release-4.0.0) to /tmp/pip-h50k8kag-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-h50k8kag-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-h50k8kag-build/
```

I saw https://github.com/nuxeo/nuxeo-drive/issues/543 which seems to be the same problem but I'm not sure I understand the answer, this is still the command shown in the readme as of 4.0.0, is the readme outdated? What is the correct way to install 4.0.0?

**Comment by BoboTiG** [comment]
Hello,

Indeed, the readme is outdated :/
I will update it to reflect real steps to install on GNU/Linux :)
