### ISSUE TITLE
Latest releases (stable or pre-release) don't sync on Windows XP

### ISSUE THREAD

**Issue by doudz** [nuxeo/nuxeo-drive#68]
Using the latest releases ; 2.0.1223 or 2.1.113, folder sync doesn't work under Windows XP Pro SP3
There's no error message, it just do nothing.

**Comment by ataillefer** [comment]
Nuxeo Drive is no more supported under Windows XP, sorry...
Yet you might want to give us an extract of the log files, could be another issue :

    C:\Users\<username>\.nuxeo-drive\logs\nxdrive.log
    C:\Users\<username>\.nuxeo-drive\logs\segfault.log

**Comment by doudz** [comment]
there's nothing in segfault.log

below the content of nxdrive.log using release 2.1.113
2016-01-14 15:17:09,838 2480 3892 WARNING  nxdrive.manager    --consider-ssl-errors option is False, won't verify HTTPS certificates
2016-01-14 15:17:09,838 2480 3892 INFO     nxdrive.manager    Handle target environment that doesn't support HTTPS verification: globally disable verification by monkeypatching the ssl module though highly discouraged
2016-01-14 15:17:09,943 2480 3892 DEBUG    nxdrive.osi        Using Windows OS integration
2016-01-14 15:17:10,013 2480 3892 DEBUG    nxdrive.engine.dao.sqlite Create DAO on C:\Documents and Settings\administrator\.nuxeo-drive\ndrive_95224451bac611e5a42d08002727cafd.db
2016-01-14 15:17:10,013 2480 3892 DEBUG    nxdrive.engine.dao.sqlite Create main connexion on C:\Documents and Settings\administrator\.nuxeo-drive\ndrive_95224451bac611e5a42d08002727cafd.db (dir exists: 1 / file exists: 1)
2016-01-14 15:17:10,025 2480 3892 DEBUG    nxdrive.engine.watcher.local_watcher Windows detected so delete event will be delayed by 2000ms
2016-01-14 15:17:10,025 2480 3892 DEBUG    nxdrive.manager    Update site URL has not been overridden in config.ini nor through the command line, using configuration from first engine [qualite]: http://community.nuxeo.com/static/drive/
2016-01-14 15:17:10,025 2480 3892 DEBUG    nxdrive.updater    Application is frozen, building Esky instance from executable C:\Program Files\Nuxeo\Drive\appdata\nuxeo-drive-2.0.1223.win32\ndrivew.exe and version finder http://community.nuxeo.com/static/drive/
2016-01-14 15:17:10,723 2480 3892 DEBUG    nxdrive.wui.application Qt / PyQt4 successfully imported
2016-01-14 15:17:10,757 2480 3892 DEBUG    nxdrive.wui.application Updated icon state to: disabled
2016-01-14 15:17:10,851 2480 3892 DEBUG    nxdrive.manager    Launch engine 95224451bac611e5a42d08002727cafd
2016-01-14 15:17:10,851 2480 3892 DEBUG    nxdrive.engine.engine Engine start
2016-01-14 15:17:10,851 2480 2672 DEBUG    nxdrive.engine.workers Thread LocalWatcher(2672) start
2016-01-14 15:17:10,851 2480 2672 WARNING  nxdrive.engine.workers Thread LocalWatcher(2672) ended with exception : AttributeError("'module' object has no attribute 'read_directory_changes'",)
2016-01-14 15:17:10,851 2480 2672 ERROR    nxdrive.engine.workers 'module' object has no attribute 'read_directory_changes'
Traceback (most recent call last):
  File "nuxeo-drive-client\nxdrive\engine\workers.py", line 140, in run
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 104, in _execute
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 500, in _setup_watchdog
AttributeError: 'module' object has no attribute 'read_directory_changes'
2016-01-14 15:17:10,885 2480 3892 DEBUG    nxdrive.wui.application Updated icon state to: asleep
2016-01-14 15:17:10,885 2480 3892 DEBUG    nxdrive.manager    Emitting started
2016-01-14 15:17:10,885 2480 3892 DEBUG    nxdrive.osi.windows.windows Registering 'None' application C:\Program Files\Nuxeo\Drive\ndrivew.exe metadata --file "%1" to registry key Software\Classes\*\shell\Nuxeo Drive\command
2016-01-14 15:17:10,885 2480 3892 DEBUG    nxdrive.osi.windows.windows Registering 'nxdrive' protocol handler to: C:\Program Files\Nuxeo\Drive\ndrivew.exe
2016-01-14 15:17:10,885 2480 3892 DEBUG    nxdrive.osi.windows.windows Registering 'Nuxeo Drive' application C:\Program Files\Nuxeo\Drive\ndrivew.exe to registry key Software\Microsoft\Windows\CurrentVersion\Run
2016-01-14 15:17:10,885 2480 3164 DEBUG    nxdrive.engine.workers Thread ProcessAutoLockerWorker(3164) start
2016-01-14 15:17:10,885 2480 3132 DEBUG    nxdrive.engine.workers Thread DriveEdit(3132) start
2016-01-14 15:17:10,885 2480 3132 DEBUG    nxdrive.drive_edit Cleanup DriveEdit folder
2016-01-14 15:17:10,885 2480 3132 DEBUG    nxdrive.drive_edit Watching FS modification on : C:\Documents and Settings\administrator\.nuxeo-drive\edit
2016-01-14 15:17:10,898 2480 288 DEBUG    nxdrive.engine.workers Thread AppUpdater(288) start
2016-01-14 15:17:10,898 2480 288 DEBUG    nxdrive.manager    Refreshing engine infos
2016-01-14 15:17:10,898 2480 2720 DEBUG    nxdrive.engine.workers Thread Tracker(2720) start
2016-01-14 15:17:10,921 2480 288 DEBUG    nxdrive.client.base_automation_client Proxy configuration: System, effective proxy list: None
2016-01-14 15:17:11,292 2480 288 DEBUG    nxdrive.engine.engine Fetched update info for engine [qualite] from server http://docs.pfi-tools.com/nuxeo/: {u'betaUpdateSiteURL': u'http://community.nuxeo.com/static/drive-tests/', u'updateSiteURL': u'http://community.nuxeo.com/static/drive/', u'serverVersion': u'7.10'}
2016-01-14 15:17:11,305 2480 288 DEBUG    nxdrive.manager    Update site URL has not been overridden in config.ini nor through the command line, using configuration from first engine [qualite]: http://community.nuxeo.com/static/drive/
2016-01-14 15:17:11,305 2480 288 DEBUG    nxdrive.updater    Polling http://community.nuxeo.com/static/drive/ for application update, current version is 2.0.1223
2016-01-14 15:17:11,467 2480 288 DEBUG    nxdrive.updater    Fetched client minimum version for server version 7.10 from http://community.nuxeo.com/static/drive/7.10.json: 2.0.1028
2016-01-14 15:17:11,723 2480 288 DEBUG    nxdrive.updater    Fetched server minimum version for client version 2.0.818 from http://community.nuxeo.com/static/drive/2.0.818.json: 5.6
2016-01-14 15:17:11,793 2480 288 DEBUG    nxdrive.updater    Fetched server minimum version for client version 2.0.911 from http://community.nuxeo.com/static/drive/2.0.911.json: 5.6
2016-01-14 15:17:11,875 2480 288 DEBUG    nxdrive.updater    Fetched server minimum version for client version 2.0.1028 from http://community.nuxeo.com/static/drive/2.0.1028.json: 5.6
2016-01-14 15:17:11,969 2480 288 DEBUG    nxdrive.updater    Fetched server minimum version for client version 2.0.1126 from http://community.nuxeo.com/static/drive/2.0.1126.json: 5.6
2016-01-14 15:17:12,049 2480 288 DEBUG    nxdrive.updater    Fetched server minimum version for client version 2.0.1216 from http://community.nuxeo.com/static/drive/2.0.1216.json: 5.6
2016-01-14 15:17:12,131 2480 288 DEBUG    nxdrive.updater    Fetched server minimum version for client version 2.0.1223 from http://community.nuxeo.com/static/drive/2.0.1223.json: 5.6
2016-01-14 15:17:12,213 2480 288 DEBUG    nxdrive.updater    Fetched server minimum version for client version 2.0.1223 from http://community.nuxeo.com/static/drive/2.0.1223.json: 5.6
2016-01-14 15:17:12,213 2480 288 DEBUG    nxdrive.updater    Client version 2.0.1223 is up-to-date regarding server version 7.10.
2016-01-14 15:17:12,213 2480 288 DEBUG    nxdrive.updater    Fetched information from update site http://community.nuxeo.com/static/drive/: update status = 'up_to_date', update version = 'None'
2016-01-14 15:17:12,213 2480 288 DEBUG    nxdrive.updater    Application is up-to-date

**Comment by doudz** [comment]
I realize this is a duplicate of https://github.com/nuxeo/nuxeo-drive/issues/63

**Comment by doudz** [comment]
looking in library.zip I found watchdog.observers contains read_directory_changes.pyc

C:\Program Files\Nuxeo\Drive\appdata\nuxeo-drive-2.0.1223.win32\library.zip\watchdog\observers\

I don't understand why it doesn't work, is there another watchdog.observers somewhere that can conflict with the one in library.zip ?

**Comment by doudz** [comment]
I found problem with the last watchdog on windows xp
Warning (from warnings module):
  File "C:\Python27\lib\site-packages\watchdog\observers\__init__.py", line 89
    warnings.warn("Failed to import read_directory_changes. Fall back to polling.")
UserWarning: Failed to import read_directory_changes. Fall back to polling.

Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\watchdog\observers\read_directory_changes.py", line 47, in <module>
    from watchdog.observers.winapi import (
  File "C:\Python27\lib\site-packages\watchdog\observers\winapi.py", line 159, in <module>
    CancelIoEx = ctypes.windll.kernel32.CancelIoEx
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CancelIoEx' not found

**Comment by ataillefer** [comment]
Yes indeed, I just saw that `read_directory_changes.` is not available under XP, see https://pythonhosted.org/watchdog/installation.html#installation-dependencies
> The Windows API provides the ReadDirectoryChangesW. watchdog currently contains implementation for a synchronous approach requiring additional API functionality only available in Windows Vista and later.

I'll try to provide a fix soon, handling the exception when trying to import read_directory_changes should do.

Thanks

**Comment by ataillefer** [comment]
Fixed in master, see https://github.com/nuxeo/nuxeo-drive/commit/c877597c6d2c594d605a0e38bb8b720917d31ebc and [NXDRIVE-525](https://jira.nuxeo.com/browse/NXDRIVE-525).

The fix will be included in next beta release.
Waiting ofr it you can test the latest developmenet build: http://qa.nuxeo.org/jenkins/view/Drive/job/nuxeo-drive-msi/1306/artifact/dist/nuxeo-drive-2.1.115-win32.msi
