### ISSUE TITLE
Nuxeo drive freezes indicating "ERROR    nxdrive.engine.workers timestamp out of range for platform localtime()/gmtime() function"

### ISSUE THREAD

**Issue by jbpotokar** [nuxeo/nuxeo-drive#70]
Hello, 

I have checked date and time on the server, and it seems ok. 
I don't really understand if the message talks about time on my client, or on the server...

2016-02-18 13:19:36,092 11356 6016 WARNING  nxdrive.engine.workers Thread LocalWatcher(6016) ended with exception : ValueError('timestamp out of range for platform localtime()/gmtime() function',)
2016-02-18 13:19:36,092 11356 6016 ERROR    nxdrive.engine.workers timestamp out of range for platform localtime()/gmtime() function
Traceback (most recent call last):
  File "nuxeo-drive-client\nxdrive\engine\workers.py", line 140, in run
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 108, in _execute
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 246, in _scan
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 507, in _scan_recursive
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 512, in _push_to_scan
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 507, in _scan_recursive
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 512, in _push_to_scan
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 507, in _scan_recursive
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 512, in _push_to_scan
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 507, in _scan_recursive
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 512, in _push_to_scan
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 507, in _scan_recursive
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 512, in _push_to_scan
  File "nuxeo-drive-client\nxdrive\engine\watcher\local_watcher.py", line 322, in _scan_recursive
  File "nuxeo-drive-client\nxdrive\client\local_client.py", line 516, in get_children_info
  File "nuxeo-drive-client\nxdrive\client\local_client.py", line 423, in get_info
ValueError: timestamp out of range for platform localtime()/gmtime() function

JB

**Comment by jbpotokar** [comment]
Ok, I found the reason !
There was a file in my local directory, that had no last update date. Windows showed an empty space there...
I found which one thanks to debug trace (great functionnality). 
Someday, it could be interesting to deal with such problematics files...

Regards !

**Comment by loopingz** [comment]
Thank you for the info. Do you know how this file was created ? We need to manage those kind of files, I'll create an issue in our JIRA system.

Regards !

**Comment by jbpotokar** [comment]
Hi!
It was previously stored on an old windows share, and recently I copied it on my local NTFS.
I can try to do it again and if it works I can send it to you...
