### ISSUE TITLE
Remote modifications are not synronized

### ISSUE THREAD

**Issue by Peter2121** [nuxeo/nuxeo-drive#71]
Nuxeo drive installed on Windows 10. Synchronization from PC to server works fine, but files added on server are never synchronized on PC.
The error message on client is:
2016-02-22 08:49:49,420 10656 11284 ERROR    nxdrive.engine.watcher.remote_watcher IncompleteRead(2701 bytes read)
Traceback (most recent call last):
  File "nuxeo-drive-client\nxdrive\engine\watcher\remote_watcher.py", line 353, in _handle_changes
  File "nuxeo-drive-client\nxdrive\engine\watcher\remote_watcher.py", line 408, in _update_remote_states
  File "nuxeo-drive-client\nxdrive\engine\watcher\remote_watcher.py", line 385, in _get_changes
  File "nuxeo-drive-client\nxdrive\client\remote_file_system_client.py", line 265, in get_changes
  File "nuxeo-drive-client\nxdrive\client\base_automation_client.py", line 372, in execute
  File "nuxeo-drive-client\nxdrive\client\base_automation_client.py", line 731, in _log_details
  File "C:\Python27\lib\socket.py", line 355, in read
  File "C:\Python27\lib\httplib.py", line 588, in read
  File "C:\Python27\lib\httplib.py", line 642, in _read_chunked
IncompleteRead: IncompleteRead(2701 bytes read)

**Comment by loopingz** [comment]
It looks like you have a network issue, you might have a server exception also that could explain why Drive cannot retrieve the changes from the server
