### ISSUE TITLE
macOS ndrive commandline invocation failed

### ISSUE THREAD

**Issue by romangaudenz** [nuxeo/nuxeo-drive#800]
command: /Applications/Nuxeo\ Drive.app/Contents/MacOS/ndrive -v
Environment: macOS 10.14 (64)
Python version installed: 3.7 + 2.7
Nuxeo Platform: LTS 2019 
Symptom: a pop up window appeard with the error message to copy:

Command line arguments:
```
-v
```
Exception:
```
Traceback (most recent call last):
  File "nxdrive/__main__.py", line 136, in main
  File "nxdrive/commandline.py", line 469, in handle
  File "nxdrive/commandline.py", line 385, in parse_cli
  File "argparse.py", line 1734, in parse_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 1972, in _parse_known_args
  File "argparse.py", line 1912, in consume_optional
  File "argparse.py", line 1840, in take_action
  File "argparse.py", line 1051, in __call__
  File "argparse.py", line 2380, in exit
SystemExit: 0
```
Logs before the crash:
```
2019-02-24 15:24:26 32730 4403512768 DEBUG    nxdrive.osi        OS integration type: macOS
```

**Comment by BoboTiG** [comment]
Hello @romangaudenz,

Thanks for the report, it will be fixed in the next release :)
