### ISSUE TITLE
ndrive not working on fedora 23

### ISSUE THREAD

**Issue by AvynerLucena** [nuxeo/nuxeo-drive#92]
After install ndrive when i call ndrive this is what happens:

[us@localhost ~]$ ndrive
Traceback (most recent call last):
  File "/usr/bin/ndrive", line 5, in <module>
    from nxdrive.commandline import main
  File "/usr/lib/python2.7/site-packages/nxdrive/commandline.py", line 17, in <module>
    from nxdrive.utils import normalized_path
  File "/usr/lib/python2.7/site-packages/nxdrive/utils.py", line 6, in <module>
    import psutil
ImportError: No module named psutil
[us@localhost ~]$ ndrive --help
Traceback (most recent call last):
  File "/usr/bin/ndrive", line 5, in <module>
    from nxdrive.commandline import main
  File "/usr/lib/python2.7/site-packages/nxdrive/commandline.py", line 17, in <module>
    from nxdrive.utils import normalized_path
  File "/usr/lib/python2.7/site-packages/nxdrive/utils.py", line 6, in <module>
    import psutil
ImportError: No module named psutil

I've already tried with different versions of Nuxeo Drive like the 1.4, but still not working.

**Comment by ataillefer** [comment]
Have you followed https://github.com/nuxeo/nuxeo-drive#ubuntudebian-and-other-linux-variants-client?
Especially:

    DRIVE_VERSION=release-2.1.427
    sudo pip install -U -r https://raw.github.com/nuxeo/nuxeo-drive/$DRIVE_VERSION/requirements.txt
    sudo pip install -U -r https://raw.github.com/nuxeo/nuxeo-drive/$DRIVE_VERSION/unix-requirements.txt
    sudo pip install -U git+https://github.com/nuxeo/nuxeo-drive.git@$DRIVE_VERSION`

**Comment by AvynerLucena** [comment]
Yes, i did all exactly as the guide says.

**Comment by ataillefer** [comment]
Seems like `psutil` needs an extra package under Fedora, can you please try:

    yum install python-psutil

**Comment by AvynerLucena** [comment]
Thanks for the help, but after installing psutil, it stills giving me errors, that i'll keep trying figure out how to solve.

Traceback (most recent call last):
  File "/usr/bin/ndrive", line 5, in <module>
    from nxdrive.commandline import main
  File "/usr/lib/python2.7/site-packages/nxdrive/commandline.py", line 15, in <module>
    from nxdrive.client.common import DEFAULT_REPOSITORY_NAME
  File "/usr/lib/python2.7/site-packages/nxdrive/client/__init__.py", line 2, in <module>
    from nxdrive.client.base_automation_client import Unauthorized
  File "/usr/lib/python2.7/site-packages/nxdrive/client/base_automation_client.py", line 13, in <module>
    from poster.streaminghttp import get_handlers
ImportError: No module named poster.streaminghttp

**Comment by AvynerLucena** [comment]
Just for information, i solved my problens when stoped trying to use ndrive on VirtualMachine, when i installed it on a real computer with fedora, it worked normally.

**Comment by ataillefer** [comment]
OK great, thanks, that's good to know!
